# Plugin: SelocoHub
# Autor: matheusdev
# Versão: 1.0.1 alpha
# Descrição: Um plugin para gerenciar o lobby e funcionalidades relacionadas.

###############################################
# CONFIGURAÇÕES GERAIS #
###############################################

# Proteção do spawn (true = ativada, false = desativada)
spawn_protection: true

###############################################
# LOBBY #
###############################################

# Localização do lobby
lobby:
  world: world  # Nome do mundo do lobby
  x: 0.0        # Coordenada X do lobby
  y: 0.0        # Coordenada Y do lobby
  z: 0.0        # Coordenada Z do lobby
  yaw: 0.0      # Rotação horizontal (yaw) do lobby
  pitch: 0.0    # Rotação vertical (pitch) do lobby

###############################################
# TELEPORTE AO ENTRAR NO SERVIDOR #
###############################################

tp-join-lobby:
  active: true          # Ativa ou desativa o teleporte ao lobby ao entrar no servidor
  only-world-lobby: false # Se true, só teleporta se o jogador deslogou no mundo do lobby

###############################################
# CONFIGURAÇÕES AO ENTRAR NO SERVIDOR #
###############################################

on-join-settings:
  clear-inventory: true # Limpa o inventário do jogador ao entrar
  heal-player: true # Enche a vida do jogador ao entrar
  set-gamemode: ADVENTURE # Define o GameMode ao entrar (Pode ser SURVIVAL, CREATIVE, ADVENTURE ou SPECTATOR)
  effects:
    speed: true # Aplica efeito de velocidade 1 ao jogador
    jump-boost: true # Aplica efeito de super pulo 1 ao jogador

###############################################
# CONFIGURAÇÕES DE JOGO #
###############################################

game-settings:
  disable-hunger: true         # Desativa a fome
  disable-damage: true         # Desativa o dano
  disable-rain: true           # Desativa a chuva
  disable-block-burn: true     # Desativa a queima de blocos
  disable-drop-item: true      # Desativa o drop de itens
  disable-item-move: true      # Desativa o movimento de itens no inventário
  disable-item-damage: true    # Desativa o dano a itens
  disable-pick-up-items: true  # Desativa a coleta de itens
  disable-explode: true        # Desativa explosões
  disable-daylight-cycle: true # Desativa o ciclo diurno

###############################################
# TELEPORTE POR DISTÂNCIA #
###############################################

teleport-distance:
  activate: true   # Ativa ou desativa o teleporte por distância
  horizontal: 150  # Distância horizontal máxima permitida
  vertical: 100    # Distância vertical máxima permitida

###############################################
# JUMPPADS #
###############################################

jumppads:
  enabled: false # Ativa ou desativa os JumpPads
  vertical: 1.5 # Potência vertical do JumpPad
  horizontal: 1.5 # Potência horizontal do JumpPad
  items:
    OAK_PRESSURE_PLATE: true
    SPRUCE_PRESSURE_PLATE: true
    BIRCH_PRESSURE_PLATE: true
    JUNGLE_PRESSURE_PLATE: true
    ACACIA_PRESSURE_PLATE: true
    DARK_OAK_PRESSURE_PLATE: true
    STONE_PRESSURE_PLATE: true
    HEAVY_WEIGHTED_PRESSURE_PLATE: true
    LIGHT_WEIGHTED_PRESSURE_PLATE: true